---
# The playbook install the cri-o container runtime interface
# to all nodes (control-plane and workers)
- hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/cor-master
  tasks:
  - name: Install dependencies
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes
  
  - name: Forwarding IPv4 and letting iptables see bridged traffic
    # Link: https://kubernetes.io/docs/setup/production-environment/container-runtimes/
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF
      sysctl --system

  - name: Add the crio apt repository
    # Link: https://github.com/cri-o/cri-o/blob/main/install.md#readme
    ansible.builtin.shell: |
      echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.26.list
      mkdir -p /usr/share/keyrings
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

  - name: Install crio-o and crio-o-runc
    apt:
      name:
        - cri-o
        - cri-o-runc
      update_cache: true
  
  - name: Enable and start crio
    ansible.builtin.systemd:
      name: crio
      state: started
      enabled: true