---
# The playbook install the dependencies for the K8S master node

- hosts: all
  become: true
  tasks:
  - name: Install Docker required system packages
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes
  
  - name: create Docker config directory
    file: path=/etc/docker state=directory

  - name: changing Docker to systemd driver
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

  - name: install Docker
    apt:
      name: docker.io
      state: present
      update_cache: true
  # - name: Add Docker’s official GPG key
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     state: present
  
  # - name: Add Docker Repository
  #   apt_repository:
  #     repo: deb https://download.docker.com/linux/ubuntu focal stable
  #     state: present
  
  # - name: Update apt and install docker-ce
  #   apt:
  #     name: docker-ce
  #     state: latest
  #     update_cache: true