---
# Get's the join command from the control plane and executes it on the workers
- hosts: control_plane
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/cor-master
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
        mitsos: "mitsos"

- hosts: workers
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/cor-master
  tasks:
    - name: join cluster
      shell: "{{ hostvars['control_plane_1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt